---
- name: install epel
  yum:
    name: epel-release
    state: present
- name: install nginx
  yum:
    name: nginx
    state: present
- name:  install index page
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html
- name: start nginx
  service:
    name: nginx
    state: started